name: experiment1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # 
  build:
    runs-on: ubuntu-latest
    #
    steps:
        - uses: actions/checkout@v3

      
        - name: Run a one-line script
          run: echo Hello, world!
        
        - name: Run a multi-line script
          run: |
           echo Add other actions to build,
           echo test, and deploy your project.
              steps:
        - uses: little-core-labs/get-git-tag@v3.0.1
          id: tagName
          with:
          tagRegex: "foobar-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
        - name: Some other step # Output usage example
          with:
          tagname: ${{ steps.tagName.outputs.tag }}
        - name: Yet another step # Environment variabl usage example
          run: |
            docker build . --file Dockerfile --tag docker.pkg.github.com/someimage:$GIT_TAG_NAME   
           
           
        
